# Generated by Django 3.0.7 on 2020-06-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('★', 1), ('★★', 2), ('★★★', 3), ('★★★★', 4), ('★★★★★', 5)], default=5, max_length=10),
        ),
    ]
