# Generated by Django 3.0.7 on 2020-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0017_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
    ]
