# Generated by Django 3.0.7 on 2020-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0019_auto_20200614_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('1점', 1), ('2점', 2), ('3점', 3), ('4점', 4), ('5점', 5)], default='5점', max_length=10),
        ),
    ]
